/**
 * SHARED SCHEDULE ENGINE
 * ----------------------
 * Both the Calendar page (events.js) and the Table View (table.js) load
 * this file and use it to compute every derived date from the anchors
 * in table-data.js. This is the ONLY place the date math lives, so the
 * two pages can never show different dates for the same thing — change
 * an anchor (or an override) in table-data.js once, and both pages
 * update.
 */

const MONTH_NAMES = [
  "January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December",
];
const MONTH_ABBR = [
  "Jan", "Feb", "Mar", "Apr", "May", "Jun",
  "Jul", "Aug", "Sep", "Oct", "Nov", "Dec",
];

function parseISO(iso) {
  const [y, m, d] = iso.split("-").map(Number);
  return new Date(y, m - 1, d);
}
function toISO(date) {
  const y = date.getFullYear();
  const m = String(date.getMonth() + 1).padStart(2, "0");
  const d = String(date.getDate()).padStart(2, "0");
  return `${y}-${m}-${d}`;
}
function addDays(date, n) {
  const d = new Date(date);
  d.setDate(d.getDate() + n);
  return d;
}
function monthNameOf(date) {
  return MONTH_NAMES[date.getMonth()];
}
function formatShort(date) {
  return `${MONTH_ABBR[date.getMonth()]} ${date.getDate()}`;
}

// Roll Sat/Sun back to the preceding Friday. Returns {date, adjusted}.
function rollToFriday(date) {
  const day = date.getDay(); // 0 = Sun, 6 = Sat
  if (day === 6) return { date: addDays(date, -1), adjusted: true };
  if (day === 0) return { date: addDays(date, -2), adjusted: true };
  return { date, adjusted: false };
}

// Steps backward N business days (skipping Sat/Sun). Always lands on a
// weekday, so callers never need to roll the result.
function subtractBusinessDays(date, n) {
  let d = new Date(date);
  let remaining = n;
  while (remaining > 0) {
    d = addDays(d, -1);
    const day = d.getDay();
    if (day !== 0 && day !== 6) remaining--;
  }
  return d;
}

// The Friday strictly BEFORE the given date. If the date is itself a
// Friday, this steps back a full week (used for Principal Meeting).
function fridayBefore(date) {
  const day = date.getDay();
  const diff = (day - 5 + 7) % 7;
  const offset = diff === 0 ? 7 : diff;
  return addDays(date, -offset);
}

// The Thursday on/before the given date (returns the date itself if it
// is already a Thursday). Used for Final Financial Review, which is
// always a Thursday and therefore never needs a weekend roll.
function thursdayOnOrBefore(date) {
  const day = date.getDay();
  const diff = (day - 4 + 7) % 7;
  return addDays(date, -diff);
}

function holidayFor(date) {
  return HOLIDAYS[toISO(date)] || null;
}

// Two board cycles' Staffing Model Updates Due would land during a full
// week school is out (Thanksgiving, Christmas) — hardcoded here to the
// Tuesday after school is back instead of the usual formula. Keyed by
// that cycle's Board Meeting date (from ANCHORS.boardMeetings).
const STAFFING_MODEL_HARDCODED = {
  "2026-12-14": "2026-12-01", // Thanksgiving week off; Tue after back (Mon 11/30)
  "2027-01-11": "2027-01-05", // Christmas week off; Tue after back (Mon 1/4)
};

// Applies a manual OVERRIDES entry (from table-data.js, generated by
// the "Save Changes" button) on top of a formula-computed value, if one
// exists for this column + cycle. Always keeps naturalISO — the value
// the formula would produce with NO override — so Table View can tell
// whether a cell has been manually changed, and can restore it later.
function applyOverride(columnKey, anchorISO, computed) {
  const naturalISO = toISO(computed.date);
  const ov = OVERRIDES[columnKey] && OVERRIDES[columnKey][anchorISO];
  if (!ov) {
    return { date: computed.date, adjusted: computed.adjusted, naturalISO, anchorISO, col: columnKey, overridden: false };
  }
  return { date: parseISO(ov), adjusted: false, naturalISO, anchorISO, col: columnKey, overridden: true };
}

// Computes every cycle from the ANCHORS in table-data.js.
function computeCycles() {
  const boardCycles = ANCHORS.boardMeetings.map((iso) => {
    const meeting = parseISO(iso);

    // Meetings in SKIP_LEADUP (table-data.js) get none of the usual
    // lead-up items — just the Board Meeting date itself.
    if (SKIP_LEADUP.has(iso)) {
      const blank = (col) => ({ date: null, adjusted: false, naturalISO: "", anchorISO: iso, col, skip: true });
      return {
        boardMeeting: { date: meeting, adjusted: false, anchorISO: iso, col: "boardMeeting" },
        boardMaterials: blank("boardMaterials"),
        finalFinancialReview: blank("finalFinancialReview"),
        financialReview: blank("financialReview"),
        staffingModel: blank("staffingModel"),
        spedSheetUpdatesDue: blank("spedSheetUpdatesDue"),
        principalMeeting: blank("principalMeeting"),
        principalMaterials: blank("principalMaterials"),
        payrollCheckIn: blank("payrollCheckIn"),
        codingCheckIn: blank("codingCheckIn"),
      };
    }

    const rawMaterials = addDays(meeting, -3);
    const materials = applyOverride("boardMaterials", iso, rollToFriday(rawMaterials));

    // Final Financial Review is always a Thursday: the Thursday on/before
    // Board Materials Ready. Financial Review is always the Thursday 7
    // days before THAT. Both are guaranteed weekdays, so neither ever
    // needs a weekend roll.
    const finalReviewDate = thursdayOnOrBefore(materials.date);
    const finalReview = applyOverride("finalFinancialReview", iso, { date: finalReviewDate, adjusted: false });

    const financialReviewDate = addDays(finalReviewDate, -7);
    const financialReview = applyOverride("financialReview", iso, { date: financialReviewDate, adjusted: false });

    // Staffing Model Updates Due = Financial Review date minus 3 days
    // (rolled back to Friday if that lands on a weekend) — unless this
    // cycle is hardcoded above (a full week off for Thanksgiving/
    // Christmas break).
    const hardcoded = STAFFING_MODEL_HARDCODED[iso];
    const rawStaffingModel = hardcoded ? parseISO(hardcoded) : addDays(financialReview.date, -3);
    const staffingModel = applyOverride("staffingModel", iso, rollToFriday(rawStaffingModel));

    // SpEd Sheet Updates Due = 2 business days before Staffing Model
    // Updates Due (its final, displayed date).
    const rawSpedSheet = subtractBusinessDays(staffingModel.date, 2);
    const spedSheetUpdatesDue = applyOverride("spedSheetUpdatesDue", iso, rollToFriday(rawSpedSheet));

    // Principal Meeting = the Friday immediately before the Board Meeting.
    const principalMeetingDate = fridayBefore(meeting);
    const principalMeeting = applyOverride("principalMeeting", iso, { date: principalMeetingDate, adjusted: false });

    // Principal Materials Ready = the day before the Principal Meeting
    // (always a Thursday, since Principal Meeting is always a Friday).
    const principalMaterialsDate = addDays(principalMeetingDate, -1);
    const principalMaterials = applyOverride("principalMaterials", iso, { date: principalMaterialsDate, adjusted: false });

    // Payroll/HR Check In and Coding Check In have no formula — they're
    // blank until you fill them in via Table View (stored as overrides).
    const payrollISO = OVERRIDES.payrollCheckIn && OVERRIDES.payrollCheckIn[iso];
    const payrollCheckIn = payrollISO
      ? { date: parseISO(payrollISO), adjusted: false, naturalISO: "", anchorISO: iso, col: "payrollCheckIn", overridden: true }
      : { date: null, adjusted: false, naturalISO: "", anchorISO: iso, col: "payrollCheckIn", overridden: false };

    const codingISO = OVERRIDES.codingCheckIn && OVERRIDES.codingCheckIn[iso];
    const codingCheckIn = codingISO
      ? { date: parseISO(codingISO), adjusted: false, naturalISO: "", anchorISO: iso, col: "codingCheckIn", overridden: true }
      : { date: null, adjusted: false, naturalISO: "", anchorISO: iso, col: "codingCheckIn", overridden: false };

    return {
      boardMeeting: { date: meeting, adjusted: false, anchorISO: iso, col: "boardMeeting" },
      boardMaterials: materials,
      finalFinancialReview: finalReview,
      financialReview: financialReview,
      staffingModel: staffingModel,
      spedSheetUpdatesDue: spedSheetUpdatesDue,
      principalMeeting: principalMeeting,
      principalMaterials: principalMaterials,
      payrollCheckIn: payrollCheckIn,
      codingCheckIn: codingCheckIn,
    };
  });

  const fcCycles = ANCHORS.financeCommittee.map((iso) => {
    const fc = parseISO(iso);
    const materials = applyOverride("financeCommitteeMaterials", iso, rollToFriday(addDays(fc, -1)));
    return {
      financeCommittee: { date: fc, adjusted: false, anchorISO: iso, col: "financeCommittee" },
      financeCommitteeMaterials: materials,
    };
  });

  const acctCycles = ANCHORS.accountingClose.map((entry) => {
    const originalISO = entry.date;
    const overrideISO = OVERRIDES.acctClose && OVERRIDES.acctClose[originalISO];
    const closeDate = parseISO(overrideISO || originalISO);
    const acctClose = {
      date: closeDate,
      adjusted: false,
      naturalISO: originalISO,
      anchorISO: originalISO,
      col: "acctClose",
      tentative: !!entry.tentative,
      overridden: !!overrideISO,
    };

    const rawDocs = addDays(closeDate, -6);
    const docsToVertex = applyOverride("docsToVertex", originalISO, rollToFriday(rawDocs));
    // A Documents-Due date that flows from a still-tentative Accounting
    // Close date is itself tentative.
    docsToVertex.tentative = !!entry.tentative;

    return { acctClose, docsToVertex };
  });

  return { boardCycles, fcCycles, acctCycles };
}

// Flattens computeCycles() into a Calendar-ready EVENTS array
// ({date, title, category, note}) — used by events.js. Also adds a
// standalone event for every School Holiday / Network Closure day in
// HOLIDAYS, so the Calendar view shows them even on days with no
// financial deadline.
function buildCalendarEvents() {
  const { boardCycles, fcCycles, acctCycles } = computeCycles();
  const events = [];

  function push(item, title, category) {
    if (!item || !item.date) return;
    const day = item.date.getDay();
    const holiday = holidayFor(item.date);
    const notes = [];
    if (item.adjusted) {
      notes.push("Moved from a weekend to this Friday");
    } else if (day === 0 || day === 6) {
      notes.push(day === 6 ? "Falls on a Saturday" : "Falls on a Sunday");
    }
    if (holiday) notes.push(`Falls on ${holiday.label}`);
    if (item.tentative) notes.push("Tentative — subject to change");
    if (item.overridden) notes.push("Manually overridden");
    events.push({
      date: toISO(item.date),
      title,
      category,
      note: notes.join("; ") || undefined,
    });
  }

  boardCycles.forEach((c) => {
    push(c.boardMeeting, "Board Meeting", "boardMeeting");
    push(c.boardMaterials, "Board Materials Ready", "boardMaterials");
    push(c.finalFinancialReview, "Final Financial Review", "finalFinancialReview");
    push(c.financialReview, "Financial Review", "financialReview");
    push(c.staffingModel, "Staffing Model Updates Due", "staffingModel");
    push(c.spedSheetUpdatesDue, "SpEd Sheet Updates Due", "spedSheetUpdatesDue");
    push(c.principalMeeting, "Principal Meeting", "principalMeeting");
    push(c.principalMaterials, "Principal Materials Ready", "principalMaterials");
    push(c.payrollCheckIn, "Payroll/HR Check In", "payrollCheckIn");
    push(c.codingCheckIn, "Coding Check In", "codingCheckIn");
  });
  fcCycles.forEach((c) => {
    push(c.financeCommittee, "Finance Committee", "financeCommittee");
    push(c.financeCommitteeMaterials, "FC Materials Ready", "financeCommitteeMaterials");
  });
  acctCycles.forEach((c) => {
    push(c.acctClose, "Accounting Close", "acctClose");
    push(c.docsToVertex, "Documents Due to Vertex", "docsToVertex");
  });

  Object.entries(HOLIDAYS).forEach(([iso, h]) => {
    events.push({
      date: iso,
      title: h.label,
      category: h.type === "closure" ? "networkClosure" : "schoolHoliday",
    });
  });

  return events;
}